### ISSUE TITLE
Static Bugmark Website

### ISSUE THREAD

**Issue by andyl** [bugmark/website#1]
We need a static HTML website for Bugmark.

Core features:
- Bugmark documentation and marketing text
- Links to Bugmark-related news and papers
- Static HTML generated by `middleman` or `jekyll`
- Use of Bootstrap4 framework with default styling and themes
- Google analytics

Extended features:
- Analytics integration to our metrics system
- Blog
- Integration to a mail-list system
- A/B testing design and implementation

**Comment by snehasi** [comment]
Hey @andyl 
I'm interested in working on this. Can I begin with a wireframe and a lo-fi prototype?

**Comment by andyl** [comment]
@snehasi - yeah that's great.  Plz tell me what tools you'd like to use for wireframe and lo-fi prototype.

**Comment by snehasi** [comment]
@andyl - I'm using Balsamiq Mockups and InVision, as of now.

**Comment by andyl** [comment]
@snehasi - perfect.  Please submit a PR with your mockups.  Let me know if you want to chat or get more input from before starting your work.  With InVision - please try to get styling as close as possible to off-the-shelf Bootstrap4.

**Comment by snehasi** [comment]
Sure.

**Comment by andyl** [comment]
@snehasi I assigned you to Issue #2.

**Comment by andyl** [comment]
This is now live on gh-pages
