### ISSUE TITLE
Landing page for ACM CI conference

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/website#18]
We agreed during our meeting today to have a https://bugmark.net/ci landing page.

- High-level info for researchers
- Contact info of all authors
- Picture of poster and downloadable PPTX and PDF
- Signup to participate in survey research
- Signup for newsletter  (sorry, GDPR requires separate check boxes for different subscriptions)

**Comment by andyl** [comment]
For the record: this was done!  Going forward: we have created a containerized lead-capture webservice at http://github.com/casmacc/lead_capture

**Comment by GeorgLink** [comment]
Yes, thank you again!
